server: 
    port: 8100
spring:
    application:
        name: book-service
    datasource:
        url: jdbc:postgresql://localhost:5432/book_service
        username: postgres
        password: 123
    jackson:
        default-property-inclusion: NON_NULL
        serialization:
            fail-on-empty-beans: false
    jpa:
        hibernate: 
            ddl-auto: update
    flyway:
        url: jdbc:postgresql://localhost:5432/book_service
        username: postgres
        user: postgres
        password: 123